### PR TITLE
Make dev server installation platform agnostic

### PR DESCRIPTION
**Pull request by matbgn**
- Uses relative path
- Override fixed IP address with localhost auto resolve one
- Removes twisted-iocpsupport from requirements.txt which is a specific build for windows only

### CODE REVIEW

**Comment by matbgn** [comment]
Just also to mention that there is no .env.exemple
`cp: cannot stat 'env/setup_dev/.env.exemple': No such file or directory`

And also there is a typo in filename .env.exemple which is .env.ex**A**mple in english ;-)

**Comment by gri38** [comment]
Hello.
Thanks a lot for your work.

Those days (and I'm about to "publish" (communicate on Joplin forum, and deprecate this project) a new project based on docker dev and publication (easy install).

I keep your work when I'll write "how to debug" on [this new project](https://github.com/joplin-vieweb/joplin-vieweb).

I also have to document a little the architecture of the sub-projects.

**Comment by matbgn** [comment]
As I understand the general idea of your "new" project I will pay attention to not saying "deprecated" because some people, for instance me, will not necessarily need all the stuff including nginx and certbot cause we already have our own proxy and certificate management.

It would be nice then if you could keep this with a minimal Dockerfile and the other for a complete docker-compose orchestration. Does it make sense?

**Comment by gri38** [comment]
you can have a look to [this diag](https://github.com/joplin-vieweb/joplin-vieweb/blob/main/README.md)

**Comment by matbgn** [comment]
Really impressive!!! Nice job!

**Comment by matbgn** [comment]
The only concern so far (I must confess I didn't really dig into it), is how you provide the basic configuration to joplin-vieweb? I mean the token and so on?

**Comment by gri38** [comment]
Hi.
Thanks.

About django server start, I create the server at container start (django-admin startproject) and only the first time I configure settings.py (create the token, set urls.py, and add authorized_host thanks to env var DOMAIN and DOMAIN_IP you must set in the main docker-compose file).

It's here: [https://github.com/joplin-vieweb/django-joplin-vieweb/blob/dev/docker/runserver.sh](https://github.com/joplin-vieweb/django-joplin-vieweb/blob/dev/docker/runserver.sh)

**Comment by matbgn** [comment]
Seems top!

Two side notes:
- Why do you keep any log level Debug in production settings? (see: https://github.com/joplin-vieweb/django-joplin-vieweb/blob/bf89470ea03d6c6225b141330463348529f15a63/settings/production.py#L21) Would it rather be possible to bypass it for security concerns?
- How do you handle the API Token for Joplin in django (oldly named JOPLIN_SERVER_TOKEN)? I can't figure out where it is at first look

**Comment by gri38** [comment]
Hi.

- Log debug in prod: good point! I should change that. (I want to make a pass on log consolidation, probably elastic suite)
- In https://github.com/joplin-vieweb/django-joplin-vieweb/blob/dev/docker/joplin_vieweb/utils.py#L186 (called in https://github.com/joplin-vieweb/django-joplin-vieweb/blob/dev/docker/joplin_vieweb/joplin.py#L45)

**Comment by gri38** [comment]
BTW: j'adore: https://www.at3flo.ch/presentation/#/start !!

**Comment by matbgn** [comment]
>     * In https://github.com/joplin-vieweb/django-joplin-vieweb/blob/dev/docker/joplin_vieweb/utils.py#L186 (called in https://github.com/joplin-vieweb/django-joplin-vieweb/blob/dev/docker/joplin_vieweb/joplin.py#L45)

Elegant! But I suppose you still use this script to inject it right?
https://github.com/joplin-vieweb/django-joplin-vieweb/blob/d8cecd3d2b14d51d38e110a9901dcf64ca84920b/env/joplin_screen.sh#L5

Would it therefore be possible to at least inject a generated token for instance with following bash command:
`pwgen 64 -s 1`

**Comment by gri38** [comment]
No I don't use anymore my screen launcher.
I'm not sure how does the joplin token works.

Previously, I used to inject 1234567890987654321 in joplin database.

but when I set the dockers... I noticed a token is present in the config file... I don't really know when it's generated...
I have to check, but I think it's generated the first time joplin terminal runs... and it will be unique per user, since it's not embed in the docker image.

**Comment by matbgn** [comment]
Ok definitely I've to give your new Dockerfile (https://github.com/joplin-vieweb/django-joplin-vieweb/blob/dev/docker/Dockerfile) a try! I'm on it. I provide you a feedback ASAP

**Comment by matbgn** [comment]
Just put some notes in this comment till I got somtehing running smoothly as BUFFER

```
Sending build context to Docker daemon  1.164MB
Step 1/21 : FROM python:3.9-alpine as compile-image
3.9-alpine: Pulling from library/python
df9b9388f04a: Pull complete 
a1ef3e6b7a02: Pull complete 
bbe9932c907b: Pull complete 
bcebe3dc2cd8: Pull complete 
8ac386379d4f: Pull complete 
Digest: sha256:561c0650e9cbaa2e4946d490c50f86631cdb21c517f42ed2d3943cdb4bf84322
Status: Downloaded newer image for python:3.9-alpine
 ---> c34fed3f67d6
Step 2/21 : COPY requirements.txt .
 ---> af933aa25460
Step 3/21 : RUN apk add --virtual .build-deps gcc libffi-dev musl-dev
 ---> Running in ad0b93369bcb
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/main/x86_64/APKINDEX.tar.gz
fetch https://dl-cdn.alpinelinux.org/alpine/v3.15/community/x86_64/APKINDEX.tar.gz
(1/16) Installing libgcc (10.3.1_git20211027-r0)
(2/16) Installing libstdc++ (10.3.1_git20211027-r0)
(3/16) Installing binutils (2.37-r3)
(4/16) Installing libgomp (10.3.1_git20211027-r0)
(5/16) Installing libatomic (10.3.1_git20211027-r0)
(6/16) Installing libgphobos (10.3.1_git20211027-r0)
(7/16) Installing gmp (6.2.1-r1)
(8/16) Installing isl22 (0.22-r0)
(9/16) Installing mpfr4 (4.1.0-r0)
(10/16) Installing mpc1 (1.2.1-r0)
(11/16) Installing gcc (10.3.1_git20211027-r0)
(12/16) Installing linux-headers (5.10.41-r0)
(13/16) Installing pkgconf (1.8.0-r0)
(14/16) Installing libffi-dev (3.4.2-r1)
(15/16) Installing musl-dev (1.2.2-r7)
(16/16) Installing .build-deps (20220405.151356)
Executing busybox-1.34.1-r5.trigger
OK: 143 MiB in 52 packages
Removing intermediate container ad0b93369bcb
 ---> dcfeb0901528
Step 4/21 : RUN pip install --user -r requirements.txt
 ---> Running in c2605f5bafcb
Collecting Django>=3.2
  Downloading Django-4.0.3-py3-none-any.whl (8.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 8.0/8.0 MB 9.2 MB/s eta 0:00:00
Collecting httpx>=0.18.1
  Downloading httpx-0.22.0-py3-none-any.whl (84 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 84.2/84.2 KB 7.1 MB/s eta 0:00:00
Collecting Markdown>=3.3.4
  Downloading Markdown-3.3.6-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.8/97.8 KB 7.2 MB/s eta 0:00:00
Collecting Pygments>=2.9.0
  Downloading Pygments-2.11.2-py3-none-any.whl (1.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.1/1.1 MB 4.9 MB/s eta 0:00:00
Collecting beautifulsoup4>=4.9.3
  Downloading beautifulsoup4-4.10.0-py3-none-any.whl (97 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.4/97.4 KB 4.2 MB/s eta 0:00:00
Collecting pymdown-extensions>=8.2
  Downloading pymdown_extensions-9.3-py3-none-any.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.3/216.3 KB 2.8 MB/s eta 0:00:00
**ERROR: Could not find a version that satisfies the requirement hyperlink_preview>=1.0.3 (from versions: none)
ERROR: No matching distribution found for hyperlink_preview>=1.0.3
The command '/bin/sh -c pip install --user -r requirements.txt' returned a non-zero code: 1**
```

**Comment by gri38** [comment]
Hi.
Thanks for feedback.

1. About joplin token, I've just checked: I add a token in joplin docker volume / settings.json
I remove the volume, start all again, and I checked: a new token is created the first time joplin launches: seems ok.
2. About the docker dev: I'll make it public when I'll add a way to configure the synchronisation (that's the purpose of x-api: configure the synch, and ask for sync). But I didnt' even started that ...
3. But your feedbacks are very welcome, and about hyperlink_prevuiew.... I've just checked if I forgot to publish on Pyi, and...:
image
I don't know if it fails because of that... let's wait the end of maintenance

**Comment by matbgn** [comment]
You were right like every time, nice catch!

Sorry for the delay I got a terrible night I have to return sleep for awhile...

My brain switched off, and I need it to tackle next error at docker launch:

```
cp: can't create '/root/.config/joplin-vieweb/settings.py': No such file or directory
sed: /root/.config/joplin-vieweb/settings.py: No such file or directory
sed: /root/.config/joplin-vieweb/settings.py: No such file or directory
sed: /root/.config/joplin-vieweb/settings.py: No such file or directory
Traceback (most recent call last):
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 259, in fetch_command
    app_name = commands[subcommand]
KeyError: 'collectstatic'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/manage.py", line 22, in <module>
    main()
  File "/app/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/root/.local/lib/python3.9/site-packages/django/core/management/__init__.py", line 266, in fetch_command
    settings.INSTALLED_APPS
  File "/root/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 87, in __getattr__
    self._setup(name)
  File "/root/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 74, in _setup
    self._wrapped = Settings(settings_module)
  File "/root/.local/lib/python3.9/site-packages/django/conf/__init__.py", line 183, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "/usr/local/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'settings.settings'

```

Executed cmd is `docker run --name joplin -p 3000:80 matbgn/joplin_vieweb:dev`

I guess I have to figure out how to pass the PATH, something in that way?

`docker run --name joplin -p 3000:80 -e PATH=/home/matbgn/.config/....... matbgn/joplin_vieweb:dev`

**Comment by gri38** [comment]
Hi.

Don't worry, I don't have much time these days either

To run the dockers containers, you must:
- Run the image joplin-terminal-x-api
- Run the image django-joplin-vieweb
- both of them should have a volume mounted to /root/.config/joplin
- django-joplin-vieweb must have a volume for its config.
- And they should be part of the same network!

I thin k the simplest way to run all that is to use a dedicated docker-compose, something like:
```
version: '3.4'

x-common-variables: &common-variables
   DOMAIN: your_domain.com
   DOMAIN_IP: 

services:
  django-joplin-vieweb:
    image: gri38/django-joplin-vieweb:latest
    depends_on:
      - joplin-terminal-xapi
    environment:
       <<: *common-variables
    restart: unless-stopped
    volumes:
      - joplin:/root/.config/joplin:ro
      - joplin-vieweb:/root/.config/joplin-vieweb
    networks:
      - joplin-net

  joplin-terminal-xapi:
    image: gri38/joplin-terminal-xapi:latest
    restart: unless-stopped
    volumes:
      - joplin:/root/.config/joplin
    networks:
      - joplin-net

volumes:
  joplin:
  joplin-vieweb:

networks:
  joplin-net: {}
```

(not tested).

However, it won't work because no port is exposed (interesting: in "my" config, I use the joplin-vieweb-nginx image which acts as proxy and exposes port. I should write a specific docker-compose for those who (like you) don't need a front nginx.

So maybe (django-joplin-vieweb's nginx listen on 8000)

```
services:
  django-joplin-vieweb:
    ...
    ports:
      - 3000:8000
```

**Pull request closed without merging**
